// This file was generated by liblab | https://liblab.com/

export interface ListPackagesParams {
  destination?: string;
  startDate?: string;
  endDate?: string;
  afterCursor?: string;
  limit?: number;
  startTime?: number;
  endTime?: number;
  duration?: number;
}
